"""added manufacturer

Revision ID: 38e5e5bda182
Revises: 1df6ef87acb3
Create Date: 2023-06-29 16:44:09.456867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e5e5bda182'
down_revision = '1df6ef87acb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=400), server_default='GENERIC', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
