"""added category

Revision ID: 57187c6c3fdd
Revises: 38e5e5bda182
Create Date: 2023-06-29 16:52:16.000565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57187c6c3fdd'
down_revision = '38e5e5bda182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key('fk_product_category', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=400), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=400), server_default=sa.text("'GENERIC'"), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_product_category'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
